name: run unit tests of main

on:
  push:
    branches: 
      'dev/*'
      
jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: run unit test
        run: |
          cd server
          mvn test
